spring:
  application:
    name: alpha-api-gateway
  profiles:
    active: core
server:
  port: 17083
#配置zuul
zuul:
  routes:
    abc: 
      path: /user-api/**
      service-id: alpha-user
    disease: 
      path: /diagnosis-api/**
      service-id: alpha-self-diagnosis
  